name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-hour
    - cron: '0 * * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: squash
          # Time zone to use. Default is UTC.
          time_zone: 'America/Los_Angeles'
          # Require all pull request statuses to be successful before
          # merging. Default is `false`.
          require_statuses_success: 'true'
          # Label to apply to the pull request if the merge fails. Default is
          # `automerge-fail`.
          automerge_fail_label: 'merge-schedule-failed'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#- name: Merge Schedule
  # You may pin to the exact commit or the version.
  # uses: gr2m/merge-schedule-action@fbb87a9d2f508b414dc5c33986efc26d8a56556a
 # uses: gr2m/merge-schedule-action@v2.4.0
  #with:
    # Merge method to use. Possible values are `merge`, `squash` or
#`rebase`. Default is `merge`.
 #   merge_method: # optional, default is merge
    # Time zone to use. Default is UTC.
  #  time_zone: # optional, default is UTC
    # Require all pull request statuses to be successful before
# merging. Default is `false`.
  #  require_statuses_success: # optional, default is false
    # Label to apply to the pull request if the merge fails. Default is
#`automerge-fail`.
 #   automerge_fail_label: # optional, default is automerge-fail
